version: 2.1

workflows:
  build-workflow:
    jobs:
      - build
      - snyk:
          context:
            - devx
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-

      - run:
          name: Build
          # Jacoco does not support incremental build so we don't run it automatically with check
          command: ./gradlew build jacocoTestReport jacocoTestCoverageVerification checkLicense

      - run:
          name: Build Legacy
          # Jacoco does not support incremental build so we don't run it automatically with check
          command: ./gradlew -p symphony-bdk-legacy build jacocoTestReport jacocoTestCoverageVerification


      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - run:
          name: Save code coverage
          command: |
            mkdir -p ~/code-coverage/jacoco/
            find . -type d -regex ".*/build/reports/jacoco/test/html" -exec cp --parents -r {} ~/code-coverage/jacoco/ \;
          when: always

      - run:
          name: Save license check results
          command: |
            mkdir -p ~/reports/dependency-license/
            find . -type d -regex "./build/reports/dependency-license" -exec cp --parents -r {} ~/reports/dependency-license/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results/junit

      - store_artifacts:
          path: ~/code-coverage/jacoco

      - store_artifacts:
          path: ~/reports/depedency-license

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

  snyk:
    docker:
      - image: cimg/openjdk:8.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-

      - run:
          name: Snyk 2.0
          command: ./gradlew snyk-test snyk-monitor

      - run:
          name: Snyk legacy
          command: cd symphony-bdk-legacy && ./gradlew snyk-test snyk-monitor
